export type Dict = Record<string, string>;

export const en: Dict = {
  "nav.features": "Features",
  "nav.how": "How it works",
  "nav.impact": "Impact",
  "nav.industries": "Industries",
  "nav.docs": "Docs",
  "btn.signIn": "Sign in",
  "btn.bookDemo": "Book a demo",
  "btn.explore": "Explore",
  "btn.tellUs": "Tell us about yours",
  "topbar.builtBy": "by",

  "hero.meetStrong": "Hi, I'm Anna.",
  "hero.meetTail": " I'm on the phones tonight — go to bed.",
  "hero.tradesLabel": "Built for home services —",
  "hero.tradesList": "HVAC · Plumbing · Roofing · Solar · Garage · Electrical · Landscaping · Cleaning · Pest Control",
  "hero.title1": "It's 11:47pm. Your phone is ringing.",
  "hero.title2": "Don't worry about it.",
  "hero.sub": "Anna answers, qualifies, quotes, and books — so your crew sleeps and your calendar fills itself.",
  "story.eyebrow": "What it feels like",
  "story.title1": "One missed call,",
  "story.title2": "turned into a booked job.",
  "story.sub": "Scroll through a single night, the way Anna actually handles it.",
  "story.s1.beat": "It's late. The phone rings.",
  "story.s1.body": "11:47pm. Your team is asleep. The competitor down the road is too. The lead has 30 seconds of patience.",
  "story.s2.beat": "Anna picks up.",
  "story.s2.body": "She greets the caller in your business's voice, asks the right qualifying questions, and learns it's a 5-window job in the living room.",
  "story.s3.beat": "Photo. Quote. Confirmed.",
  "story.s3.body": "The customer texts a photo. Anna measures from the image, drafts a $3,540 estimate, and offers a Tuesday 9:30 AM survey slot — all before they go to bed.",
  "story.s4.beat": "You wake up booked.",
  "story.s4.body": "Morning coffee. One survey on the calendar, one estimate already sent, one deposit waiting. You haven't touched the phone.",
  "story.s4.foot": "All overnight. No one was awake.",

  "hero.oss": "Open-source · AGPL-3.0",
  "hero.star": "★ Star on GitHub",
  "hero.selfHost": "Self-host or done-for-you setup",

  "features.eyebrow": "Features",
  "features.title": "Configure once. Captures every lead.",
  "features.sub": "Set your business hours, pricing rules, and service area. Hearthline adapts to your trade — from emergency plumbing at 2 AM to a $25k solar quote at noon.",
  "features.f1.name": "AI Phone Receptionist",
  "features.f1.body": "Never miss a call again. Hearthline picks up every inbound within two rings, qualifies the lead in real time, and books the slot directly into your team's calendar — in a voice you choose, with the script your business runs on.",
  "features.f2.name": "AI Chat Assistant",
  "features.f2.body": "Web chat, SMS, and WhatsApp — same Anna, same memory of the customer. Replies in seconds, hands off to a human only when she should.",
  "features.f3.name": "CRM Integration",
  "features.f3.body": "Every call, text, and quote pushes into your CRM as a clean record — HubSpot, Pipedrive, Jobber, ServiceTitan, or your own Postgres.",
  "features.f4.name": "Smart Quoting",
  "features.f4.body": "Customers text a photo. Anna measures with vision, drafts line items, applies your tax + margin rules, and sends a Stripe-ready estimate.",
  "features.f5.name": "AI Knowledge Base",
  "features.f5.body": "Drop in your warranty doc, service catalog, and FAQ. Anna quotes your real terms — never invents a price or a promise you don't make.",
  "features.f6.name": "Data Analytics",
  "features.f6.body": "Live dashboards on call volume, lead quality, conversion, and revenue per channel — so you can prove the night shift is paying for itself.",

  "stats.eyebrow": "Why teams switch",
  "stats.title": "Every missed call is a job your competitor books.",
  "stats.body": "Hearthline picks up every inbound across every channel, qualifies it on the spot, and hands your crew a deal-ready conversation. Anna never sleeps, never takes a smoke break, and never forgets to ask for the photo.",
  "stats.li1": "Calls answered while you're on a roof at 3 AM",
  "stats.li2": "Photos turned into drafted quotes before you finish your coffee",
  "stats.li3": "Every interaction synced to HubSpot, Pipedrive, or your CRM",
  "stats.card1.num": "3 AM",
  "stats.card1.label": "The burst-pipe call your competitor missed last Tuesday. Anna picked it up.",
  "stats.card2.num": "43 sec",
  "stats.card2.label": "Average time from customer photo to drafted PDF quote in tonight's demo.",
  "stats.card3.num": "$0",
  "stats.card3.label": "Per missed call. Hearthline books the ones your inbox loses.",

  "flow.eyebrow": "How it flows",
  "flow.title": "How a job flows through Hearthline.",
  "flow.sub": "Five stages, fully automated. The customer never feels the handoffs — they just get a quick answer, a quote, and a booked time slot.",

  "convo.eyebrow": "A real conversation",
  "convo.title": "Anna handles the objection, not just the hello.",
  "convo.sub": "Live SMS thread between Anna and a customer. Photo arrives, quote drafted, deal created, calendar booked — all auto.",
  "convo.head.title": "Inbound Lead Automation",
  "convo.head.sub": "Qualifies the lead, syncs to CRM, drafts an estimate — automatically.",
  "convo.msg1": "I need to replace about 5 windows in my living room. Looking for white PVC.",
  "convo.msg2": "Got it — 5 PVC windows, white. Standard double-glazed, or do you want triple for noise / energy? And could you snap a quick photo of one window from inside?",
  "convo.msg3": "Double-glazed is fine. Here's a photo.",
  "convo.msg4Pre": "Perfect — measured ~120×140 cm from your photo. Five units, supply and install: ",
  "convo.msg4Mid": " incl. tax. I've texted the breakdown and a Tuesday 9:30 AM survey slot. Tap the link to confirm.",
  "convo.output": "Output Result",
  "convo.estimate": "Estimate #E-291 · sent",
  "convo.deal": "Deal Created · HubSpot",
  "convo.survey": "Survey Booked · Tue 9:30 AM",
  "convo.signed": "— Anna",

  "industries.eyebrow": "Trades",
  "industries.title": "One platform. Every trade.",
  "industries.sub": "Pricing logic, scripts, and dispatch rules come pre-tuned for each trade — and are fully editable. Don't see yours? Hearthline configures to any home-service workflow.",
  "industries.note": "Plus: not in this list? Hearthline plugs into any workflow your team already runs. ",
  "industries.i1.name": "HVAC & Plumbing",
  "industries.i1.body": "Emergency-call routing 24/7, technician dispatch, maintenance contracts.",
  "industries.i2.name": "Windows & Doors",
  "industries.i2.body": "Photo quoting, measurement scheduling, installation bookings.",
  "industries.i3.name": "Solar & Roofing",
  "industries.i3.body": "Roof-type qualification, rebate matching, site-survey coordination.",
  "industries.i4.name": "Energy Renovation",
  "industries.i4.body": "Insulation audits, subsidy applications, multi-step renovation flows.",
  "industries.i5.name": "Garage & Shutters",
  "industries.i5.body": "Brand + model identification, repair vs replace triage, after-hours calls.",
  "industries.i6.name": "Electrical",
  "industries.i6.body": "Emergency vs scheduled job triage, safety-warning scripts, smart-home upsells.",
  "industries.i7.name": "Landscaping & Pools",
  "industries.i7.body": "Seasonal scheduling, recurring contracts, photo-based estimates.",
  "industries.i8.name": "Cleaning & Restoration",
  "industries.i8.body": "Damage triage, insurance routing, recurring booking, before/after photos.",
  "industries.i9.name": "Pest Control",
  "industries.i9.body": "Symptom triage, recurring contracts, neighbour-coverage upsell, follow-ups.",

  "config.eyebrow": "Configurable end-to-end",
  "config.title": "Your voice. Your pricing. Your CRM. Your hours.",
  "config.body": "Pick from 30+ neural voices in 7 languages. Drop in your price book. Connect HubSpot, Pipedrive, Salesforce, ServiceTitan, or your custom API. Set business hours per channel. Hearthline runs on your rules — not the other way around.",
  "config.k1.l": "Voice",
  "config.k1.v": "30+ neural · 7 languages",
  "config.k2.l": "Pricing",
  "config.k2.v": "Your price book · per-trade rules",
  "config.k3.l": "CRM",
  "config.k3.v": "HubSpot · Pipedrive · Salesforce · API",
  "config.k4.l": "Hours",
  "config.k4.v": "Per-channel · per-day · holidays",
  "config.k5.l": "Voice cloning",
  "config.k5.v": "Use your owner's voice (optional)",
  "config.k6.l": "Self-host",
  "config.k6.v": "AGPL-3.0 code on GitHub (commercial license available)",

  "finalCta.title": "Keep the fire on. We'll watch the door.",
  "finalCta.sub": "Anna picks up the 3 AM emergency, the lunch-break callback, and the photo from the customer who can't describe a leak in words. Your team stays on the tools — the schedule fills itself.",

  "footer.tag": "The 24/7 AI communication hub for home-service teams.",
  "footer.product": "Product",
  "footer.resources": "Resources",
  "footer.legal": "Legal",
  "footer.faq": "FAQ",
  "footer.privacy": "Privacy",
  "footer.terms": "Terms",
  "footer.builtBy": "Built by",
  "footer.bio": "AI build-along videos for developers shipping real agents. Hire me to deploy Hearthline for your business.",
  "footer.copyright": "Open-source under AGPL-3.0. Commercial license available.",
  "footer.bottomTail": "with care for home-service teams.",

  "lang.label": "Language",
};

export function tEn(key: string): string {
  return en[key] ?? key;
}
